[ARC-1904] create Layouts
AleksandreGalogreBaramidze/Quiz-Application pull request #1
Opened 2021-11-12 12:16 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1904

2021-11-13 07:57 UTC, giorgiqemoklidze approved these changes

2021-11-15 09:59 UTC, AnaRusadze requested changes

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +        with(holder.binding){
with(holder.binding.checkerImageView)

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +            checkerImageView.setOnClickListener {
checkerImageView.setOnClickListener ის მაგივრად პირდაპირ setOnClickListener

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +                    holder.binding.checkerImageView.setBackgroundResource(R.drawable.unchecked)
პირდაპირ setBackgroundResource

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +class BackGroundCustomView @JvmOverloads constructor(
ცუდი სახელია

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +    private var ovalHeight = BASE_OVAL_HEIGHT
ჯობია რომ ამ კლასშივე გეწეროს companion object, რომ private იყოს

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +        roundedCornerIsUpsideDown =
ეს აღარ დაგჭირდება scaleYის გამო

2021-11-15 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +    private val bgRectangle: Rect
ოვალი და რექთი რომ არ გქონდეს, ორი ობიექტის მაგივრად შეგიძლია pathი გამოიყენო lineTo და arcTo ფუნქციებით

2021-11-17 18:26 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +            checkerImageView.setOnClickListener {
done

2021-11-17 18:26 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +                    holder.binding.checkerImageView.setBackgroundResource(R.drawable.unchecked)
done

2021-11-17 18:26 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +class BackGroundCustomView @JvmOverloads constructor(
done

2021-11-17 18:26 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +    private var ovalHeight = BASE_OVAL_HEIGHT
done

2021-11-17 18:27 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +        roundedCornerIsUpsideDown =
done

2021-11-17 18:27 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/costumview/BackGroundCustomView.kt
> +    private val bgRectangle: Rect
done

2021-11-17 20:09 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +        with(holder.binding){
done

2021-11-18 08:40 UTC, andguladzeshio approved these changes

2021-11-22 14:31 UTC, AnaRusadze requested changes

2021-11-22 14:31 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +            }
setBackgroundResource(if(!isChecked) R.drawable.checked else R.drawable.unchecked)

ერთ ხაზშიც შეიძლებოდა

2021-11-22 14:31 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/home/HomeFragment.kt
> +        binding.NameTextView.text = "$username:$score"
ვიუმოდელისაა ეს ლოგიკები

2021-11-22 15:59 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/adapters/QuestionsRecyclerAdapter.kt
> +            }
done

2021-11-22 16:00 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/home/HomeFragment.kt
> +        binding.NameTextView.text = "$username:$score"
რეალურად ამას ესე აღარ ვიყენებ სხვა ფუშებში და მთლიანად ამოვიღე, ლოგიკურად იმ ფუშებს მიეკუთვნება

2021-11-22 16:01 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapplication/ui/home/HomeFragment.kt
> +        const val DEFAULT_SCORE = 0
წინა რადგან წავშალე ამას აღარ ვიყენებდი და ესეც ამოვიღე

2021-11-22 16:09 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-25 08:30 UTC, AnaRusadze approved these changes

2021-11-25 08:30 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapplication/ui/costumview/RectCustomView.kt
> +        val color = ContextCompat.getColor(context, R.color.black)
შეგიძლია ფერების წამოღება ექსთენშენში გაიტანო

2021-11-25 08:30 UTC, merged